pre-commit:
  jobs:
    - name: eslint
      glob: '*.{js,jsx,ts,tsx,astro}'
      run: pnpm exec eslint {staged_files}

    - name: stylelint
      glob: '*.{css,sass,scss}'
      run: pnpm exec stylelint {staged_files}
