import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Header = () => {
  return (
    <header>
      <nav>
        <menu>
          <li>
            <Link href="/">トップ</Link>
          </li>
          {/* <li> */}
          {/*   <Link href="/books">ブック</Link> */}
          {/* </li> */}
        </menu>
      </nav>
    </header>
  );
};

const Footer = () => {
  return <footer>{/* footer */}</footer>;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <title>文庫サーチ</title>
      </head>
      <body className="dark">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
